using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Content.Client.UserInterface.Controls;
using Content.Shared.Botany;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.Botany.DnaManipulator;

[GenerateTypedNameReferences]
public sealed partial class PlantDnaManipulatorWindow : FancyWindow
{
    public PlantDnaManipulatorWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(PlantDnaManipulatorBoundUserInterfaceState state)
    {
        SeedInfo.Children.Clear();
        if (!state.HasSeed)
        {
            SeedInfo.AddChild(new Label { Text = Loc.GetString("plant-dna-manipulator-window-no-seed") });
            return;
        }
        if (state.SeedName != null)
            SeedInfo.AddChild(new Label { Text = state.SeedName });
        if (state.Attributes != null)
        {
            foreach (var (key, value) in state.Attributes)
            {
                SeedInfo.AddChild(new Label { Text = $"{key}: {value}" });
            }
        }
    }
}
