using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.Controls;
using Content.Client.Message;
using Robust.Shared.Utility;

namespace Content.Client.Botany.PlantScanner.UI;

[GenerateTypedNameReferences]
public sealed partial class PlantScannerWindow : DefaultWindow
{
    public PlantScannerWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(string info)
    {
        Info.SetMarkup(info);
    }
}
